### ISSUE TITLE
Erratum in the DolphinDB Tutorial_EN

### ISSUE THREAD

**Issue by mengmengsui** [dolphindb/Tutorials_EN#2]
In the first paragraph in https://github.com/dolphindb/Tutorials_EN/blob/master/database.md#34-list-domain, 
it reads: The **different** between a list domain and a value domain is that XXX...
It should read: The **difference** between a list domain and a value domain is that XXX.

**Comment by yiwenqian00** [comment]
Thank you! This issue has been fixed.
